name: referral_bot
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  teledart: ^0.6.1
  path_provider: ^2.1.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

asset:
 - assets/referrals.json
 - assets/config.json
 - .env
